# Read the Docs - ubuntu20-mamba410
FROM readthedocs/build:ubuntu20-base

# Define Python versions to be installed via asdf
ENV RTD_PYTHON_VERSION mambaforge-4.10.1-5

# Labels for external usage
LABEL python.version=$RTD_PYTHON_VERSION

# Install supported Python versions
RUN asdf install python  $RTD_PYTHON_VERSION && \
    asdf global python $RTD_PYTHON_VERSION

CMD ["/bin/bash"]
